NODE_ENV=dev

PORT=8090
HOST=https://fb-bot.nguyencongminh.dev
TZ=Asia/Ho_Chi_Minh

# MongoDB config
MONGODB_USERNAME=admin
MONGODB_PASSWORD=Vqn61bLc5ZX3Df5T
MONGODB_HOST=bot-fithou.yzsredf.mongodb.net
MONGODB_REPLICA_SET=
MONGODB_NAME=fithou-bot
MONGODB_PROTOCOL=mongodb+srv

# Jobs
FITHOU_JOB_HOUR=0
FITHOU_JOB_MINUTE=30
FITHOU_JOB_SECOND=5

FITHOU_URL=http://www.fithou.edu.vn
CTMS_URL=http://ctms.fithou.net.vn

FB_VERIFY_TOKEN=EAAUUdOUxO6YBAOh4mcJmTQ4UdyWRwXIr8SzBAyIBC58IJcPiMLu9nz1y7c2bO4REUXJDtwYa3eVNVZAFA70lmwOUMXxfPiw43ZCyoiuh9T3rhWsyN3VFIDvZCZClk7kTeBDOU7YdRwkYeQsabn4zZBEUZCxcjJAcb4KDUjT6S1gRFkSGB9KLlpagd1VIADohNmQDHjTvCAFgZDZD
APP_CODE=c830f4093a4c7aba55eb123c439cf365

AUTH_KEY=MinhVu113